# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-10 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20170618_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycontactmodel',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='mycontactmodel',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Email'),
        ),
    ]
