# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-10 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_auto_20170618_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Проекти'},
        ),
    ]
